M48
; DRILL file {KiCad 7.0.6} date Mon Nov  6 13:05:40 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-06T13:05:40-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X123.36Y-114.4
X137.36Y-114.4
T2
X127.718Y-86.284
X135.418Y-86.284
T3
X113.74Y-85.8
X113.74Y-120.8
X148.74Y-85.8
X148.74Y-120.8
T0
M30
